### PR TITLE
ListFeed class with row deletion capability. 

### PR DESCRIPTION
**Pull request by bashantad**
added Worksheet#list_feeds method to fetch list of rows
rectified Worksheet#list_feed_url method as old method is no longer working
added ListFeed class
ListFeed#delete method to delete a row

### CODE REVIEW

**Comment by gimite** [comment]
Thanks for the pull request. There is already a list feed style object which you can get by Worksheet#list (though implemented using cell-based feed):
http://gimite.net/doc/google-drive-ruby/GoogleDrive/Worksheet.html#method-i-list
I prefer to implement the feature in it, using cell-based feed, instead of adding a new class.

**Comment by bashantad** [comment]
The reason I had to create another class is because cell-based feed doesn't allow to delete a row. However, list-based feed allows you to delete a row in google sheets. 
Ref: https://developers.google.com/google-apps/spreadsheets/?hl=en#deleting_a_list_row
According to google sheets documentation. 

    The two types of batch operations supported are query and update. insert and delete are not supported because the cells feed cannot be used to insert or delete cells.

**Comment by gimite** [comment]
You can virtually delete a row with a cell-based feed by moving all cell values below the row by one. It has some limitation that it doesn't work with cell formatting and inter-cell expressions, though. List-based feed also has a limitation that it cannot delete the first row, I believe.

**Comment by gimite** [comment]
Worksheet#delete_rows was added at: https://github.com/gimite/google-drive-ruby/commit/b756cd764a4c9f17372276ec5f7954e1692a7cec

**Pull request closed without merging**
