### PR TITLE
url to id fix for new google drive

### PR DESCRIPTION
**Pull request by prcongithub**

### CODE REVIEW

**Comment by gimite** [comment]
Thanks for the pull request. I will take a look.

**Comment by prcongithub** [comment]
Any update?

**Comment by gimite** [comment]
Sorry for slow response. I tried it but export_as_string worked without your change. Didn't it work for you?

**Comment by gimite** [comment]
I found that you branched from a very old version (in the age of 0.3.x). Anyway 0.3.x no longer works. It should work if you write like this with the latest version:
```
p ss.worksheets[0].export_as_string
```

**Comment by prcongithub** [comment]
session.collection_by_url(url) this method now throws error for new google drive folders.
This fix resolved the problem. I could close this PR and send another one checked out from v1.0.1, does that work?

**Comment by gimite** [comment]
Thanks for the report. I can reproduce the issue, and I pulled part of your change related to it at:
https://github.com/gimite/google-drive-ruby/commit/92a06d7517ac0375a355afa0bee4da3f5dd95d7e

**Pull request closed without merging**
