### PR TITLE
only installed application works

### PR DESCRIPTION
**Pull request by grosser**
was confused at first since I chose web and got a weird error message, this might be helpful ...

@gimite

### CODE REVIEW

**Comment by grosser** [comment]
@gimite rebased

**Comment by grosser** [comment]
@gimite

**Comment by gimite** [comment]
Sorry, I'm recently busy and is making slow progress, but I'm trying to update the doc to cover both command line app and web app use cases. This should be resolved as the part of the update.

**Comment by gimite** [comment]
Sorry for late. I have updated README.

**Pull request closed without merging**
