### PR TITLE
cleaned up session.rb a bit

### PR DESCRIPTION
**Pull request by defenestrator**
Just cleaning up and making rubocop happy.

### CODE REVIEW

**Comment by gimite** [comment]
Thanks for the pull request. The format looks good, but can you also update other files? The current format of session.rb is consistent with other files. I don't want to change format of just one file.

**Comment by defenestrator** [comment]
Sure, sounds good. I can look at doing that in the next couple of days.

**Comment by gimite** [comment]
#194 did this for all files.

**Comment by defenestrator** [comment]
Hooray! Life got weird for me, and I forgot about this. Life is always weird for everyone, I guess. Haha

**Pull request closed without merging**
